# Generated by Django 5.0 on 2023-12-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='this is the name of the publisher', max_length=50)),
                ('website', models.URLField(help_text='this is the website of the publisher')),
                ('email', models.EmailField(help_text="this is the publisher's email address", max_length=20)),
            ],
        ),
    ]
